# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-03 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者id')),
                ('sid', models.IntegerField(verbose_name='被滑者id')),
                ('mark', models.CharField(choices=[('dislike', '左滑'), ('like', '右滑'), ('superlike', '超级喜欢')], max_length=20, verbose_name='滑动的类型')),
                ('stime', models.DateTimeField(auto_now_add=True, verbose_name='滑动时间')),
            ],
        ),
    ]
