# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-04 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=0, verbose_name='用户的会员id'),
        ),
    ]
